## Sesi 4

Numpy

In [1]:
import numpy as np

In [3]:
firstArray = np.array([1, 2, 3, 4])

In [4]:
firstArray

array([1, 2, 3, 4])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.2 Add, Remove, Sort

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [14]:
arr = np.append(arr, [1,2])

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [16]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [17]:
np.sort(arr)

array([1, 1, 2, 2, 3, 4, 5, 6, 7, 8])

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                          [0, 1, 2, 3]],
                          
                          [[0, 1, 2, 3],
                           [0, 1, 2, 3]],
                          
                          [[0, 1, 2, 3],
                           [0, 1, 2, 3]]])
                            

In [24]:
array_example

array([[[0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [25]:
array_example.ndim

3

In [26]:
array_example.shape

(3, 2, 4)

In [27]:
array_example.size

24

## 1.4 Reshape

In [28]:
a = np.arange(6)

In [29]:
a

array([0, 1, 2, 3, 4, 5])

In [30]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [32]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

## 1.5 Conver 1D to 2D

In [33]:
a

array([0, 1, 2, 3, 4, 5])

In [34]:
a.shape

(6,)

In [36]:
a2 = a[np.newaxis]

In [37]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [38]:
a2.shape

(1, 6)

In [39]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [41]:
a3 = a[:, np.newaxis]

In [42]:
a3.shape

(6, 1)

In [45]:
b2 = np.expand_dims(a, axis=1)

In [46]:
b3 =np.expand_dims(a, axis=0)

In [47]:
b2.shape

(6, 1)

In [48]:
b3.shape

(1, 6)

In [49]:
a

array([0, 1, 2, 3, 4, 5])

## 1.6 Indexing & Slicing

In [50]:
a

array([0, 1, 2, 3, 4, 5])

In [51]:
print(a)
print(a[0])
print(a[2])

[0 1 2 3 4 5]
0
2


In [52]:
a[0:4]

array([0, 1, 2, 3])

In [53]:
a[2:]

array([2, 3, 4, 5])

In [55]:
a[:4]

array([0, 1, 2, 3])

In [56]:
a[-1]

5

In [57]:
newArray = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

In [58]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
newArray[newArray>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [60]:
newArray[newArray<5]

array([1, 2, 3, 4])

In [62]:
newArray[(newArray>2) & (newArray< 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## 1.7 Create Array from Existing Data

In [66]:
arr = np.arange(1, 11)

In [67]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr1 = arr[3:8]

In [72]:
arr1

array([4, 5, 6, 7, 8])

In [73]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [75]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [76]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

1.8 Array Opeartions

In [79]:
data = np.array([1,2])

In [81]:
ones = np.ones(2)

In [82]:
data + ones

array([2., 3.])

In [83]:
data.sum()

3

In [84]:
a

array([0, 1, 2, 3, 4, 5])

In [85]:
a.sum()

15

In [92]:
b = np.array([[1, 2], [1, 2]])

In [89]:
b.sum()

6

In [95]:
b.sum(axis=0)

array([2, 4])

In [94]:
b.sum(axis=1)

array([3, 3])

In [96]:
data

array([1, 2])

In [99]:
data = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18]])

In [100]:
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [101]:
data.sum()

171

In [102]:
data.sum(axis=0)

array([21, 24, 27, 30, 33, 36])

In [103]:
data.sum(axis=1)

array([21, 57, 93])

In [104]:
data.min()

1

In [105]:
data.max()

18

In [106]:
data.min(0)

array([1, 2, 3, 4, 5, 6])

In [107]:
data.min(axis=1)

array([ 1,  7, 13])

## 1.9 Matirces

In [110]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [111]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [113]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [114]:
np.random.random((4,5))

array([[0.98385639, 0.48108834, 0.75134764, 0.83876973, 0.93936306],
       [0.25898597, 0.6997431 , 0.47377403, 0.83251622, 0.77855956],
       [0.43721601, 0.80939946, 0.80558264, 0.55950789, 0.10247402],
       [0.06546109, 0.73151139, 0.6977999 , 0.31393437, 0.59566854]])

In [116]:
data = np.array([[1,2],[3,2]])

In [117]:
ones = np.ones((2, 2))

In [118]:
data

array([[1, 2],
       [3, 2]])

In [119]:
ones

array([[1., 1.],
       [1., 1.]])

In [120]:
data+ones

array([[2., 3.],
       [4., 3.]])

In [121]:
data - ones

array([[0., 1.],
       [2., 1.]])

## 1.10 Dot Product

In [122]:
a_1 = np.array([[1, 2,3], [4, 5, 6]])

In [123]:
a_2 = np.array([[7,8], [9,10], [11,12]])

In [124]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
a_2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [126]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## 11 Indexing and slicing

In [127]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [128]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
data [0]

array([1, 2])

In [130]:
data [1]

array([3, 4])

In [131]:
data [2]

array([5, 6])

In [132]:
data [0, 1]

2

In [133]:
data [1,1]

4

In [134]:
data [1,0]

3

In [135]:
data [1:3]

array([[3, 4],
       [5, 6]])

In [136]:
data[0:3]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [138]:
data[0:2, 0]

array([1, 3])

## 1.12 Transposing

In [139]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [140]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])